### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by cklm** [backup-manager/symfony#3]
Hi, I would like to use this bundle with Symfony 3.2 - but version 1.0 only supports Symfony 2.x. Since it's a bad practice to relay on dev-master, can you please tag a version 1.1?
Thanks!

**Comment by cklm** [comment]
Anything new here? :)

**Comment by ShawnMcCool** [comment]
@lhpalacio Hey, should we go ahead and tag this?

**Comment by lhpalacio** [comment]
@ShawnMcCool Yes, that's ok. I'll do it now.

**Comment by ShawnMcCool** [comment]
K, no problem. I really wouldn't mind also doing it. If I can ever help you just let me know.

**Comment by cklm** [comment]
Thank you!
