### ISSUE TITLE
Bundle does not work with Symfony 3

### ISSUE THREAD

**Issue by djenniex** [backup-manager/symfony#30]
I installed the bundle as directed in the README. However, I get the following error when trying to run the Symfony Console:

> [Symfony\Component\Console\Exception\LogicException]
>   The command defined in "BM\BackupManagerBundle\Command\BackupCommand" cannot have an empty name.

This is easily fixed by passing a name to the parent constructor of the BackupCommand class a string.

ie. `parent::__construct('bp:backup');`

**Comment by Nyholm** [comment]
Thank you for this issue. What version of smfony are you running?

**Comment by Nyholm** [comment]
Yeah. okey. You are correct

The docs differs from 3.3 to 3.4: https://symfony.com/doc/3.3/console/commands_as_services.html

Could you add `->setName(self::$defaultName)` in the (configure function) on both commands?
