### ISSUE TITLE
undefined method named "scalarPrototype" - Symfony 3.2

### ISSUE THREAD

**Issue by ymezard** [backup-manager/symfony#31]
Hi,
I installed the bundle on my Symfony 3.2 project.
I get this exception :

> UndefinedMethodException in Configuration.php line 92:
> Attempted to call an undefined method named "scalarPrototype" of class "Symfony\Component\Config\Definition\Builder\ArrayNodeDefinition".

scalarPrototype method seems to be included on the 3.3 version.
Do you think you can use the old method to extends the compatibility?

> New in version 3.3: The arrayPrototype() method (and the related booleanPrototype() integerPrototype(), floatPrototype(), scalarPrototype() and enumPrototype()) was introduced in Symfony 3.3. In previous versions, you needed to use prototype('array'), prototype('boolean'), etc.

Thanks

**Comment by Nyholm** [comment]
Hm, Can you investigate if there is an easy fix. Symfony 3.2 is not officially supported anymore. So we should see if there is an easy fix or update our composer.json to only support 3.3+

**Comment by Nyholm** [comment]
okey, Can you submit a PR?

**Comment by ymezard** [comment]
Hello, 
So I submited a PR last week.
Do you plan to add it to master branch?

**Comment by Nyholm** [comment]
Of course. Sorry, I must have missed that. It is now merged

**Comment by bGaetan** [comment]
Hi !
It's possible to merge the PR ? we are actually blocked by this issue.

thanks a lot

**Comment by Nyholm** [comment]
There I've merged both PRs. Thank you

**Comment by bGaetan** [comment]
thanks @Nyholm. You will create a new release for this fix ? or  I've to point my composer on dev-master ?

**Comment by Nyholm** [comment]
I will try to verify this during the weekend and tag a new release on Monday if not before
