### ISSUE TITLE
The service "backup_manager.command.backup" tagged "console.command" must be public.

### ISSUE THREAD

**Issue by bGaetan** [backup-manager/symfony#36]
Hi !

I've this error : 'I worked on SF 2.8
```
InvalidArgumentException in AddConsoleCommandPass.php line 32:
The service "backup_manager.command.backup" tagged "console.command" must be public.
```

According to this issue https://github.com/FriendsOfSymfony/FOSJsRoutingBundle/issues/306 and the   stof comment, I think it can be a better way to said that command are public

**Comment by Nyholm** [comment]
Thank you for this issue and the reference. I've create #38 which will fix this issue.
