### ISSUE TITLE
DropboxV2 type not being recognized

### ISSUE THREAD

**Issue by mhaque02** [backup-manager/symfony#46]
DropboxV2 is not being recognized. Any fix for this? 

In composer.json, the appropriate Dropbox library is included
`"backup-manager/backup-manager": "^1.2"`
`"srmklive/flysystem-dropbox-v2": "^1.0",`

![issue](https://user-images.githubusercontent.com/1075631/37366251-4a17bf66-26d6-11e8-9cad-ef50e7cdaaa2.PNG)

**Comment by mhaque02** [comment]
Function `getConfigTreeBuilder()` in `DependencyInjection/Configuration.php` does not include any mentions of DropboxV2, just Dropbox

**Comment by Nyholm** [comment]
Thank you for this issue. You are correct. Have a look at #47. That one should solve your issue.

**Comment by Nyholm** [comment]
I've merged it to master. Please try it before I tag a new release.

**Comment by mhaque02** [comment]
This is fine now - thanks!

**Comment by Nyholm** [comment]
Excellent. Tagging new release now
