### ISSUE TITLE
Docummentation and configuration

### ISSUE THREAD

**Issue by ecorpet** [backup-manager/symfony#5]
I'm using your bundle to make backups but there are 2 issues : 

- doc from symfony2 bundle is not uptodate according to this line : $manager->makeBackup()->run('development', [new Destination('s3', 'test/backup.sql')], 'gzip');  from https://github.com/backup-manager/backup-manager

- you should add a very important parameter "ignoreTables" option in Configuration

                            ->arrayNode('ignoreTables')
                                ->prototype('scalar')->end()
                            ->end()

And i would abandon my fork to come back to your bundle ;)

thanks !

**Comment by ShawnMcCool** [comment]
@lhpalacio does this make sense?

@ecorpet any chance for a pull request?

**Comment by wartab** [comment]
I can confirm that the doc is not accurate

**Comment by ecorpet** [comment]
hello Shawn
i've made the pull request with all updates  . hope its ok !
regards

**Comment by lhpalacio** [comment]
Hey @ecorpet 
> doc from symfony2 bundle is not uptodate according to this line : $manager->makeBackup()->run('development', [new Destination('s3', 'test/backup.sql')], 'gzip'); from https://github.com/backup-manager/backup-manager

Using Symfony bundle you can do this, it's the same thing. This is in the documentation.
`$this->container->get('backup_manager')->makeBackup()->run('development', 's3', 'test/backup.sql', 'gzip');`

> you should add a very important parameter "ignoreTables" option in Configuration

Yes, I agree with you. #6

**Comment by ecorpet** [comment]
Because the signature of the method is `public function run($database, array $destinations, $compression) {`

Logically  `$this->container->get('backup_manager')->makeBackup()->run('development', 's3', 'test/backup.sql', 'gzip');` should not work .

I've tried and ...  it does not work.
Maybe I'm not using it correctly ?

**Comment by wartab** [comment]
Try this:

```php
$destination = new Destination("s3", $fileName);
$backup = $this->get("backup_manager")->makeBackup();
$backup->run("development", [$destination], "gzip");
```

**Comment by ecorpet** [comment]
@wartab logical ,

It's the same than `$manager->makeBackup()->run('development', [new Destination('s3', 'test/backup.sql')], 'gzip');` I've proposed in my first message of this thread  ;-) 
So it's logical, it's working

**Comment by wartab** [comment]
Didn't see that, just thought you needed help on getting it to work :)

But as you mentioned, the doc here should indeed be adapted to the doc from the main repo.

**Comment by lhpalacio** [comment]
@ecorpet I understand now!

The signature of the method was changed in version 1.1.1 of backup-manager. :(

So, at the moment, this module only supports version 1.1.0.

Thank you for warning me.
