### ISSUE TITLE
Symfony 5 support

### ISSUE THREAD

**Issue by nmeirik** [backup-manager/symfony#62]
The bundle does not appear to support the newly released Symfony 5. When attempting to upgrade an installation with the software installed, I get the following error:

```
backup-manager/symfony 2.2.0 requires symfony/console ^2.7 || ^3.1 || ^4.0 -> satisfiable by symfony/console[v4.3.8] but these conflict with your requirements or minimum-stability.
```

**Comment by nmeirik** [comment]
https://github.com/backup-manager/symfony/pull/63

**Comment by Nyholm** [comment]
Thank you
