### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by louan-dubois** [backup-manager/symfony#79]
Hi, I am encountering problems during installation of the bundle. I'm working with Symfony 5.1.8 (but the project originally started with Symfony 2), php 7.4.9 with wamp 3.2.3.3. I'm using the 3.1.1 version of BackupManager
As written in the README, I installed the bundle with `composer require backup-manager/symfony`. It worked well, so I configured the yaml and then directly used the line `$this->container->get('backup_manager')->...` in my Controller. I got an the following error : 

![image](https://user-images.githubusercontent.com/53853773/100119653-624afe80-2e77-11eb-9667-1ed0527f35e7.png)

As it told me, I tried dependency injection with
`use BackupManager\Manager;` passing `Manager $manager` in my function and replaced `$this->container->get('backup_manager')->` by `$manager->` and inserted `BackupManager\Manager: ~` in my `services.yaml`
Then I got the error : 

![image](https://user-images.githubusercontent.com/53853773/100120472-3f6d1a00-2e78-11eb-89bc-c48dbdbf934a.png)

I looked at the file `BM\BackupManagerBundle\BMBackupManagerBundle` and it is empty, is it normal ? Shouldn't it insert all the classes for autowiring ? 
I'm new to Symfony so don't hesitate to correct me I may make mistakes.
Thank you very much

**Comment by Nyholm** [comment]
That makes sense. 

You should not use objects from the container directly anymore. Try to inject `BackupManager\Manager` into your service with container injection instead. 

In your `services.yaml` also write: 

```yaml
services:
  BackupManager\Manager: '@backup_manager'
```

I will update the docs and fix this in next release. 

-------

> I looked at the file BM\BackupManagerBundle\BMBackupManagerBundle and it is empty, is it normal ?

Yes. 

> Shouldn't it insert all the classes for autowiring ?

No

**Comment by louan-dubois** [comment]
Many thanks ! The bundle is now working. But now I got an error "mysqldump is not recognised as an internal command", even if the full path to the bin folder has been added to the path, and it works on my cmd.

**Comment by Nyholm** [comment]
Cool cool cool. 

Thank you for letting me know
